### ISSUE TITLE
Variable type change from group item to elementary item -> enhance syntax check for undefined PIC value

### ISSUE THREAD

**Issue by sergiuilie** [eclipse/che-che4z-lsp-for-cobol#102]
If a variable type changed at the compile/run time because of the poor definition of level data and the group item is not followed by a nested variable (a child) then our LSP should apply a check in order to see if the PIC value is defined.

![image](https://user-images.githubusercontent.com/23320888/70808211-79582400-1dbf-11ea-8cdc-5e7e54daf981.png)

In the example above we should see a syntax error on the VAR3 definition.

**Comment by jellypuno** [comment]
VAR100 and VAR200 is also invalid

**Comment by temanbrcom** [comment]
Fixed by #717
