### ISSUE TITLE
References are displayed twice

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#103]
I am testing the FIND ALL REFERENCES and it is showing me the result twice.

![code4z findreferences](https://user-images.githubusercontent.com/45042840/70834073-a5909680-1df9-11ea-8377-a913469d007a.gif)

Same with Peek Definition

![Capture2](https://user-images.githubusercontent.com/45042840/70834090-b0e3c200-1df9-11ea-8ee3-8beb92338b4a.PNG)

**Comment by sergiuilie** [comment]
@temanbrcom @zacanbrcom is not this a behavior of the client? I checked our server and we are sending the correct information.

**Comment by temanbrcom** [comment]
@sergiuilie Yes, this is reproducible only on Theia. We've noticed this behavior a long time ago. I'm not sure that we may do anything with that, but we should check. Maybe there is some additional configuration required on the server.

**Comment by ishche** [comment]
Is there issue on the Theia repository for that? If the lsp message correct, then it should be very common error.

**Comment by sergiuilie** [comment]
@ishche nothing found, do you suggest to open on theia repository or che-theia?

**Comment by ishche** [comment]
@sergiuilie sounds like theia issue. You can double-check in theia spectrum [chat](https://spectrum.chat/theia).

**Comment by jellypuno** [comment]
If it helps, I re-created it in VSCode and not Theia and Both Cobol (bitlang) and Cobol LSP extensions is activated for me.

**Comment by temanbrcom** [comment]
I've just reproduced it on VS Code with paragraph definition
![image](https://user-images.githubusercontent.com/47776865/73930119-4ec5ab80-48d6-11ea-8b86-a47148b8c717.png)

**Comment by temanbrcom** [comment]
Also, now all the references for variables on VS Code are displayed twice 
![image](https://user-images.githubusercontent.com/47776865/73930422-bed43180-48d6-11ea-9c37-8dda058e9c33.png)

**Comment by temanbrcom** [comment]
The behavior reproduces only for local files, for those ones opened with Zowe everything is fine

**Comment by davsc01** [comment]
I get this behavior using ZE and VS Code.

**Comment by VitGottwald** [comment]
Fresh install of ZOWE Explorer and Code4Z. Opened a remote cobol file from the Open Mainframe Project Cobol Course. Also getting double references as described above.

**Comment by VitGottwald** [comment]
Using VSCode.

**Comment by grianbrcom** [comment]
When the user tries to find all references, one set of references generated from our plugin the second set cames from "bitlang.cobol" plugin. Now, "bitlang.cobol" is not a part of Code4Z package.
I think that we could mark the bug as resolved.
