### ISSUE TITLE
support floating comment indicators (*>)

### ISSUE THREAD

**Issue by GitMensch** [eclipse/che-che4z-lsp-for-cobol#1039]
**Describe the solution you'd like**
Appropriate syntax highlighting; it already seems to work in the language server.

**Current non-handling**
![image](https://user-images.githubusercontent.com/6699539/127319331-0cac8986-08c2-4b69-91ac-fdae4ff467d7.png)

**Additional information**
See documentation at [Enterprise COBOL for z/OS > Reference-Format > Floating comment indicators (*>)](https://www.ibm.com/docs/en/cobol-zos/6.3?topic=b-floating-comment-indicators).

**Comment by temanbrcom** [comment]
Thank you for reporting!

@grianbrcom please, check the coloring tooling.
