### ISSUE TITLE
command 'cobol-lsp.smart-tab' not found

### ISSUE THREAD

**Issue by GitMensch** [eclipse/che-che4z-lsp-for-cobol#1040]
## Description ##
Installed version 0.20 on a new vscode installation, the opened a cbl file which was correctly highlighted as COBOL, then marked a block I wanted to indent and pressed [TAB], got a message "command 'cobol-lsp.smart-tab' not found".

## Expected behavior ##
Indentation working, both [TAB] and [SHIFT]+[TAB].

**Comment by temanbrcom** [comment]
Thank you for reporting!
@Nurkambay please, take a look at it.

**Comment by GitMensch** [comment]
@temanbrcom you may want to assign this issue to @Nurkambay if this is his to inspect, too.

**Comment by temanbrcom** [comment]
> if this is his to inspect, too.
This is what I am trying to figure out.

**Comment by Nurkambay** [comment]
Hi, @GitMensch 
The root cause of this issue is that the extension does not handle an event

**The most likely causes are:**
1. The extension did not initialised properly
1. VS Code did not recognised a file as a COBOL file

**What to do**:
- Check if you have any warnings and errors after opening a COBOL file
- Ensure that file was recognised by VS Code as a COBOL file (in the right conner must be a "COBOL" label)
<img width="641" alt="Screenshot 2021-10-05 at 11 53 44" src="https://user-images.githubusercontent.com/10369965/136001496-25ee1f38-3f68-4fc0-bab2-b449276d9272.png">

- Remove all other extensions related to COBOL and try again

**Comment by GaloisGirl** [comment]
In my case, I have an uncaught exception:

`Exception has occurred: Error: An error occurred collecting all configurations from the profile root directory "C:\Users\awroc\.zowe\profiles". Please supply the configurations on the profile manager constructor parameters OR initialize the profile manager environment. Details: Profile IO Error: An error occurred attempting to read all profile directories from "C:\Users\awroc\.zowe\profiles". Error Details: ENOENT: no such file or directory, scandir 'C:\Users\awroc\.zowe\profiles'`

I'm not using Zowe or anything, just some plain COBOL compiled via `cobc -xj file.cob`. This is my only COBOL-related extension installed.

Then the extension displays the error "Java 8 is not found", not sure why, as I do have 1.8.0_301, but that triggers the `return` in `activate` in [https://github.com/eclipse/che-che4z-lsp-for-cobol/blob/development/clients/cobol-lsp-vscode-extension/src/extension.ts#L65](extension.ts#L65) , before the key handlers are bound. Commenting out the `return` solves the `'cobol-lsp.smart-tab' not found ` problem.

**Comment by temanbrcom** [comment]
> In my case, I have an uncaught exception:
> 
> `Exception has occurred: Error: An error occurred collecting all configurations from the profile root directory "C:\Users\awroc\.zowe\profiles". Please supply the configurations on the profile manager constructor parameters OR initialize the profile manager environment. Details: Profile IO Error: An error occurred attempting to read all profile directories from "C:\Users\awroc\.zowe\profiles". Error Details: ENOENT: no such file or directory, scandir 'C:\Users\awroc\.zowe\profiles'`
> 
> I'm not using Zowe or anything, just some plain COBOL compiled via `cobc -xj file.cob`. This is my only COBOL-related extension installed.
> 
> Then the extension displays the error "Java 8 is not found", not sure why, as I do have 1.8.0_301, but that triggers the `return` in `activate` in https://github.com/eclipse/che-che4z-lsp-for-cobol/blob/development/clients/cobol-lsp-vscode-extension/src/extension.ts#L65 , before the key handlers are bound. Commenting out the `return` solves the `'cobol-lsp.smart-tab' not found ` problem.

Please, make sure that the java directory is added to the PATH environment variable. Also, you may try installing the [Zowe Explorer](https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe) extension, it will create the `user/.zowe` directory, so the error should disappear. Then you may uninstall it if you don't need it.

Kind regards,
Andrei Temnikov

**Comment by GitMensch** [comment]
Please ensure that this extension creates user/.zowe if it really needs it.

**Comment by GitMensch** [comment]
The original issue of the error message is not happening with 1.0.0
