### ISSUE TITLE
SKIP* considered as Syntax error

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#105]
![Capture1](https://user-images.githubusercontent.com/45042840/70834491-cb6a6b00-1dfa-11ea-9686-fa5c61fa6c8d.PNG)

https://www.ibm.com/support/knowledgecenter/SSQ2R2_9.1.1/com.ibm.ent.cbl.zos.doc/PGandLR/ref/rlcdsski.html

It is written in the working storage area like this:
```
01 Var1
     03 Var2
...
     03 Var25
SKIP2
01 Var26
     05 Var 27
```

**Comment by zacanbrcom** [comment]
Hello Jessielaine, thanks for your issue.
We're aware about this problem and is in our plan address it.
A.
