### ISSUE TITLE
Introduce Completion Suggestions for Copybook Names

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#106]
## Description ##
Michelle wants to have all the copybook names that are used in the current COBOL file, as well as those that present in the workspace to be suggested if autocomplete is invoked. 

## Acceptance Criteria ##
- Copybook names that are already used in the current document are listed after paragraphs and before snippets with kind "Reference"
- Copybook names that are present in the current workspace are listed after used ones with kind "File"
- No documentation providing is required
- The solution is covered with tests
- The solution is tested on all the platforms

**Comment by zimlu02** [comment]
Support for **local** copybooks released in 1.0.0.
Support for **remote** to come.

**Comment by ishche** [comment]
@zimlu02 let's have a separate story for remote copybooks completion. https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/1554
