### ISSUE TITLE
Incomplete COPY REPLACING Produces NPE

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#1080]
## Description ##

A `COPY REPLACING` statement with an unclosed pseudo text wrapper produces NPE

## Steps to reproduce ##
1. Add a copy statement with an unclosed pseudo text: `COPY CUST2COB REPLACING ==`
2. See server freezes

## Expected behavior ##

The document is parsed as expected

**Comment by ap891843** [comment]
Let me try to fix this.
