### ISSUE TITLE
Increase Code Coverage for Databus

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#111]
## Description ##
As a software engineer, I would like to have my code covered with tests.

## Acceptance criteria ##
- Code coverage for ```lsp-core-domain``` module is more 80%. The current value is 0%
- Coverage is made with unit tests, not use cases in service in order to keep the coverage module-related.

**Comment by zacanbrcom** [comment]
Increase coverage for following packages:
- [ ] [0%] **com.broadcom.lsp.domain.cobol.model**
- [ ] [0%] **com.broadcom.lsp.domain.cobol.databus.impl**
- [ ] [3%] **com.broadcom.lsp.domain.cobol.databus.api** 
- [ ] [0%] **com.broadcom.lsp.domain.cobol.factory**
- [ ] [0%] **com.broadcom.lsp.cdi.module.databus**
- [ ] [0%] **com.broadcom.lsp.cdi.module**
