### ISSUE TITLE
Need for configurable .c4z folder

### ISSUE THREAD

**Issue by GitMensch** [eclipse/che-che4z-lsp-for-cobol#1114]
**Is your feature request related to a problem?**
Totally - I'm on a read-only workspace - and get
> File error: Error: EPERM: operation not permitted, mkdir 'x:\workspace1\folder1\.c4z'

**Describe the solution you'd like**
A new setting to define the folder (in my case it would be set to `C:\Userspace\c4z\workspace1`), ideally with resolving other configuration variables (in my case `C:\Userspace\c4z\${config:my.wsName}`)

Related: #336 which got the fixed ".c4z folder" added.

**Comment by GitMensch** [comment]
As requested: pinging @zimlu02 about this to be one of the issues I see.

I _think_ there was an API to write to "extension specific storage" that may could be used instead (if I remember correctly that would write somewhere in the local user application data); this may could be used, too - otherwise I'm totally fine with a configurable folder.

**Comment by GitMensch** [comment]
another friendly ping @zimlu02

**Comment by zimlu02** [comment]
> another friendly ping @zimlu02

Hi Simon, I am really sorry for this long silence. We've finally got to this issue and I will follow up on this ticket this week with more info.

**Comment by VitGottwald** [comment]
Hello @GitMensch, are you using the copybook download feature to retrieve copybooks from z/OS?

**Comment by GitMensch** [comment]
No, I'm only doing PC-based COBOL (with GnuCOBOL, including big iron dialects [Enterprise COBOL, MVS, BS200, GCOS]).

**Comment by VitGottwald** [comment]
Thank you @GitMensch . I created a bug https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/1716 to fix the current behaviour.
