### ISSUE TITLE
Windows Defender Firewall has blocked the language_server.exe

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#113]
Is this a normal behaviour? 

![Capture](https://user-images.githubusercontent.com/45042840/70924995-cbe94880-202a-11ea-81da-ee30b3f7e19f.PNG)

**Comment by temanbrcom** [comment]
@jellypuno Thank you for the reporting. It is not a part of our solution, I'll forward it to the maintainers.
