### ISSUE TITLE
Asterisk is in different columns when CTRL + / is used for commenting

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#117]
![Capture](https://user-images.githubusercontent.com/45042840/71094617-8f912600-21ab-11ea-9df8-8f716a0e6ff5.PNG)

I tried commenting my cobol code using CTRL+/ and the asterisk goes to  different columns

**Comment by temanbrcom** [comment]
Hello @jellypuno,

Thank you for reporting!
This capability is provided by the Bitlang plugin and is a third-party issue.
