### ISSUE TITLE
Add '.COPY' to the list of copybook extensions

### ISSUE THREAD

**Issue by roman-kupriyanov** [eclipse/che-che4z-lsp-for-cobol#1173]
**Is your feature request related to a problem?**

There is a problem with automatic activation of COBOL LSP plugin in VScode for retrieved Endevor elements of a copybook type. The retrieved elements can be stored in a workspace with addition of a `.copy` extension to them and it is not recognized by the plugin by default. The `COBOL Copybook` language can be selected manually for each of copybook files, but it would be a nice touch to activate the plugin without any additional steps.

**Describe the solution you'd like**

Add an extra `.copy` extension to the list for `COBOL Copybook` to be able to recognize such file extensions too.

**Describe alternatives you've considered**

None.

**Additional information**

None.

**Comment by zimlu02** [comment]
Would the proposed solution to provide a list of extensions in the settings work for you?
https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/1046

**Comment by roman-kupriyanov** [comment]
> Would the proposed solution to provide a list of extensions in the settings work for you?
> #1046

Hi Lukas! Thanks for checking it out.

A configurable list of extensions is definitely a good addition to the plugin and may resolve this problem if the user would preconfigure the `.copy` or any other custom extensions. 
But since the `.copy` extension is used in some other products as a default extension for copybooks, it leads to the unavoidable extra configuration steps, which must be done when someone just starts to work with the plugin. In terms of interability between the products and user experience this may not be expected and may be a cause for additional documentation efforts as well.

Maybe an addition of the `.copy` to the default copybook extensions can be considered together with implementation of the configurable extensions feature.

**Comment by zimlu02** [comment]
I see. Yes, there can be default values set to `.cpy` and `.copy`.
