### ISSUE TITLE
Detecting Errors.

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#118]
If there is already a detected error, new errors are not displayed anymore. (No period in Configuration Section)
Also quick fix does not fix the errors.

![Capture](https://user-images.githubusercontent.com/45042840/71095903-af294e00-21ad-11ea-9050-2602d90a55f6.PNG)

**Comment by temanbrcom** [comment]
Thank you for this issue!
We will check what is going on with error detection. 
As for quick fixes, it is not supported yet. We will announce this feature additionally later on.

**Comment by zimlu02** [comment]
Closing due to not valid syntax.
