### ISSUE TITLE
Go to Definition doesn't work on variables

### ISSUE THREAD

**Issue by arjunlawagon** [eclipse/che-che4z-lsp-for-cobol#1181]
## Description ##
'Go to Definition' and 'Go to Reference' doesn't work on variables. But works on copybooks.

## Steps to reproduce ##
1. Go to a variable within PROCEDURE DIVISION
2. Right click on any variable and select 'Go to Definition' or 'Go to References'
3. See error.

## Expected behavior ##
As per Features details, the definition of the variable should be opened or shown.

## Screenshots ##
Selecting variable for 'Go to Definition' option
![image](https://user-images.githubusercontent.com/31883336/141079885-0d0ee526-5e37-4e03-8ccc-ae33d31c5cf0.png)

No definition found error
![image](https://user-images.githubusercontent.com/31883336/141080061-9ff09646-4cbe-443d-9b8b-00b93768bb64.png)

Works when 'Go to Definition' used on copybooks.
![image](https://user-images.githubusercontent.com/31883336/141081086-c08f3963-2c71-4141-b7cb-423902b2a756.png)

Copybook definition opened.
![image](https://user-images.githubusercontent.com/31883336/141081281-fbf10fb8-72ed-4d8c-904d-298718cfa3fe.png)

## Environment ##
 - OS: Windows 10 Pro
 - IDE: VS Code 1.62.1
 - Cobol Language Support v0.20.0 and v0.21.0

## Additional information ##
No other cobol related extensions installed in VSCode at the same time.
Apologies if this issue looks dumb, but I really how it's able to access copybooks directly, it saves a lot of time.

**Comment by temanbrcom** [comment]
Hi @arjunlawagon,

Thank you for reporting. Could you please show the definition of the variable MPEACK-ID?

Kind regards,
Andrei Temnikov

**Comment by arjunlawagon** [comment]
Hi @temanbrcom 

MPEACK-ID is defined in the WORKING-STORAGE SECTION in the program. The same error for variables defined within a copybook.
![image](https://user-images.githubusercontent.com/31883336/141096983-26b52168-dd20-4a68-ac2f-4a854912a1f6.png)

**Comment by temanbrcom** [comment]
I have some thoughts about what is going on, but I need the logs to be sure. Could you, please, provide me with them?

First, please select "ALL" for the logging level in the plugin setting:
![image](https://user-images.githubusercontent.com/47776865/141142130-1295a085-bc51-48e5-bca1-338f7f72e08b.png)

Then, please, try to reproduce the scenario. The logs will be in this file: C:\Users\<user name>\LSPCobol\logs\app.log. Please, send it to me.

Thank you.
