### ISSUE TITLE
Add content areas A and B support

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#12]
**Description:**
As a software engineer, I would like to differentiate between areas in COBOL as fixed format implies so I can validate more input and show correct diagnostic messages.

**Acceptance criteria:**

- Area A and Area B text preprocessing
- Validate items which depend on area A or B

**Definition of Done:**
This US will be completed once all dependencies are completed and use cases are implemented.
Example of use case:​​​​​​ 

1. IDENTIFICATION DIVISION should start in Area A
2. Differentiate between areas
3. Validate where IDENTIFICATION keyword begins
4. Publish diagnostic

**Comment by GitMensch** [comment]
Question: is this implementation currently "fixed format only"?

Additional to the COBOL 2002+ standardized free-form reference-format there are some additional formats like ACUCOBOL-GTs "terminal format" - are those supported and if not is it possible to have a switch to toggle or would it need a separate implementation for this (likely sharing most of the code)?

**Comment by zacanbrcom** [comment]
Hi @GitMensch - at moment we support only fixed format.
For the second question we'll back to you asap.

**Comment by sergiuilie** [comment]
Hello @GitMensch 

Our focus is to support IBM's implementation of standards, not the standards themselves. So we are currently supporting fixed format only as of now.
This [PR](https://github.com/eclipse/che-che4z-lsp-for-cobol/pull/437) will add Area A and B support, I suggest you give it a try with our new release. 

Thank you for your interest!
