### ISSUE TITLE
Copybook has wrong syntax errors

### ISSUE THREAD

**Issue by ekuether** [eclipse/che-che4z-lsp-for-cobol#1211]
## Description ##

When I use a copy/replacing command in a Cobol program, there are two items that the copybook/cobol program do not recognize as valid code. 
The first is that any "redefines" that come after a 66 Level Number are not recognized. 
As shown in the "Screen Shots Section", my Redefine line does occur right after the redefined item. Removing that 66 renaming line, and it recognizes the redefine.

The second copybook issue is that group names in the form 'XXX'-GROUP-NAME, (Literally a name that looks exactly like that with the single ticks around the XXX), is not recognized as a valid group name. However, IBM systems do recognize that as a valid group name for a copy/replacing statement. See the screenshots below for a better example.

##
 Steps to reproduce ##
Use the example code in the screen shots to reproduce. 

## Expected behavior ##

The expected behavior is that there will be no syntax errors relating to these issues. 

## Screenshots ##

66 Level Number Screen Shots.
![Level 66 error 1](https://user-images.githubusercontent.com/96203346/146386686-be001d1f-bbda-4e7f-963d-ea83fab5ed6c.png)
![Level 66 error 2](https://user-images.githubusercontent.com/96203346/146386743-4a14917f-a89d-4ef3-b462-946bf5228c12.png)

Single Tick Error Examples
![Single tick error 4](https://user-images.githubusercontent.com/96203346/146388959-2b7a618c-8693-43eb-8e0f-5ec896b241b9.jpg)
![Single tick error 3](https://user-images.githubusercontent.com/96203346/146389001-2bac7e05-7703-484a-a27e-62aaac78fec4.jpg)

## Environment ##
 
VS Code for Windows 10

**Comment by temanbrcom** [comment]
Hi @ekuether,

Thank you for reporting! 
I could reproduce it. I will let you know when we fix it.

**Comment by temanbrcom** [comment]
The replacing issue was fixed in #1216. To be published within the next release.
