### ISSUE TITLE
Defining paths to different types of copybooks is not resolved correctly

### ISSUE THREAD

**Issue by nalmabrcom** [eclipse/che-che4z-lsp-for-cobol#1251]
## Description ##
Defining paths to different types of copybooks is not resolved correctly, unique names should be resolved as well, but in fact, the copybook is resolved always on the first `COPY` statement. 

## Steps to reproduce ##
1. Apply the settings. 
2. Open the source file. 
3. Perform 'Go to Definition' on each copybook with the name `local`. 

## Expected behavior ##
 `COPY MAID local.` should refer to `copybooks/maid/local`
 `COPY local.` should refer to `copybooks/local`
 `COPY IDMS local.` should refer to `copybooks/idms/local`

## Actual behavior ##
If the first copybook statement is MAID , as in this source example, then all subsequent copybooks will refer to the MAID folder too.
The same behavior is for local and IDMS statements. 

## Environment ##
 - Build: [877](https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/development/877/)
 - OS: Windows 10
 - IDE: [e.g. VS Code,

## Additional information ##
settings.json 
```
{
    "cobol-lsp.cpy-manager.paths-local": [
        "copybooks"
    ],
    "cobol-lsp.cpy-manager.maid.paths-local": [
        "copybooks/maid"
    ],
    "cobol-lsp.cpy-manager.idms.paths-local": [
        "copybooks/idms"
    ]
}
```

source:
```
       Identification Division.
       Program-id. HELLO-WORLD.

       Procedure Division.
           COPY MAID local.
           COPY local.
           COPY IDMS local.

           COPY localLocal.
           COPY MAID localMaid.
           COPY IDMS localIdms.
           Stop Run.

```

**Comment by GitMensch** [comment]
Is `"cobol-lsp.cpy-manager.maid.paths-local"` an unreleased feature? 0.21.0 does not provide that.
