### ISSUE TITLE
Updating of a copybook is not reflected in main cobol program

### ISSUE THREAD

**Issue by VitGottwald** [eclipse/che-che4z-lsp-for-cobol#1266]
## Description ##

Copybook changes do not trigger refresh of analysis in programs containing those copybooks.

## Steps to reproduce ##
1. Create a cobol program referencing an empty copybook `LVL5.cpy`
``` cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HelloWorld.

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       INPUT-OUTPUT SECTION.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
        01  LVL1.
          03 LVL3.
             COPY LVL5.

       PROCEDURE DIVISION.
           DISPLAY "Hello World".
           STOP RUN..
```
2. Error is displayed on `03 LVL3.` because the copybook is empty.
3. Update the `LVL5.cpy` copybook with `       05 FROM-COPY PIC X(8).`
4. Error is still show on the `03 LVL.`.

## Expected behavior ##
Error on `03 LVL3.` is cleared out because the copybook is no longer empty and contains a valid declaration.

## Screenshots ##
 
<img width="783" alt="Screenshot 2022-02-15 at 11 54 21" src="https://user-images.githubusercontent.com/19686979/154047961-b608c852-199e-425f-a71d-4af44ba6da5d.png">

**Comment by temanbrcom** [comment]
AFAIK, auto-saving does not produce a file system event right away, so copybook cache cannot be invalidated. It is rather a VSC bug than ours.

**Comment by VitGottwald** [comment]
I tried dragging and dropping the copybook within VSCode's tree, in macOS finder app, also tried creating the copybook from a command line through `vi` and also via `echo '       05 FROM-COPY PIC X(8).' >! copybooks/COBOL/LVL5.cpy`. VSCode properly detects the file and shows it in the file explorer tree, but Cobol analysis is not refreshed.

**Comment by VitGottwald** [comment]
Also, I have auto-save turned off in VSCode.

**Comment by VitGottwald** [comment]
Testing on current development 040e6773d2d7949a06f1ccbb3d0b04c2309aded1.

**Comment by VitGottwald** [comment]
Works with latest build as of today.
