### ISSUE TITLE
Support for CICS MAP

### ISSUE THREAD

**Issue by azarrafa** [eclipse/che-che4z-lsp-for-cobol#1364]
Hello,
Is there any plan to support CICS MAPs in the copybook ?

**Comment by ap891843** [comment]
@azarrafa Could you please provide a sample program and a corresponding copybook, for us to have a look at?

**Comment by azarrafa** [comment]
This is a snippet for exemple the main cobol MAINPGM, I have the two copybook DFHAID and DFHBMSCA locally no problem here but when I add the CICS MAP  MAINMAP I get this error below : 

**Syntax error on 'DFHMSD' expected {CBL, END, EXEC, FILE, ID, IDENTIFICATION, LINKAGE, LOCAL-STORAGE, PROCEDURE, PROCESS, WORKING-STORAGE, '01-49', '66', '77', '88'}COBOL Language Support - E**


>       IDENTIFICATION DIVISION.                                                 
>        PROGRAM-ID. MAINPGM.                                                     
>        AUTHOR.     .                                                
>       ******************************************************************        
>       *DESCRIPTION:Main menu program my update                         *        
>       ******************************************************************        
>        ENVIRONMENT DIVISION.                                                    
>        CONFIGURATION SECTION.                                                   
>        SOURCE-COMPUTER.    IBM-PC.                                              
>        OBJECT-COMPUTER.    IBM-PC.                                              
>        DATA DIVISION.                                                           
>        WORKING-STORAGE SECTION.                                                 
>                                                                                 
>            COPY MAINMAP.                                                       
>                                                                                                                                                                                                                    
>            COPY DFHAID.                                                         
>                                                                                 
>            COPY DFHBMSCA.                                                       
>                                                                                 
 
And here a snippet of my map : 

> MAINMAP  DFHMSD TYPE=&SYSPARM,                                         C        
>                LANG=COBOL,                                             C        
>                CTRL=(FRSET,FREEKB),                                    C        
>                EXTATT=YES,                                             C        
>                TIOAPFX=YES,                                            C        
>                COLOR=TURQUOISE,                                        C        
>                MODE=INOUT                                                       
> MAINMAP  DFHMDI SIZE=(24,80)                                                    
>          DFHMDF INITIAL=' ',                                           C        
>                POS=(1,1),                                              C        
>                LENGTH=1,                                               C        
>                ATTRB=(ASKIP,BRT)

**Comment by azarrafa** [comment]
Thanks for your help, I will close this issue
