### ISSUE TITLE
LSP save missing copybook names into the .dep file

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#141]
## Description
The user open a cobol file into the editor. LSP start in background to analyze the code, producing syntax and semantic information back to the user.
If a copybook is required by the main cobol file and LSP server is not able to found it, the server should add the copybook name as item in a .dep file that will be created for the current opened document.
If the .dep file doesn't exists LSP server will create it, otherwise it will try to open the file and update the dependency file with a new item.
In meanwhile a semantic warning is sent back to the user to inform that the required copybook has not been found.

## Acceptance Criteria
- The solution is not breaking the existing implementation (i.e. if copybook is not found still user should see a semantic information in the editor)
- The .dep file is correctly created/updated and available for the copybook manager extension

## Technical Notes
- The databus will produce a new type of event that could be in the future observed by others
- A set of unit tests are provided to verify edge scenarios (.dep not exists, .dep is not writable/corrupted, copybook name already exists, .dp is a temp folder and so on)

**Comment by ishche** [comment]
Folder for .dep files should be "${workspace}/.cobdeps".

**Comment by zacanbrcom** [comment]
Will follow another proper issue for the extension part that download the missing copyboos
