### ISSUE TITLE
Diagnostics of copybook disappear on didClose

### ISSUE THREAD

**Issue by ishche** [eclipse/che-che4z-lsp-for-cobol#1505]
Diagnostics of copybook disappear on didClose even if the main program is still open.
It's expected that diagnostics will be deleted only if the user has closed the main program.

Probably it's related to our didClose implementation (org.eclipse.lsp.cobol.service.CobolTextDocumentService#didClose):
```
  @Override
  public void didClose(DidCloseTextDocumentParams params) {
    if (disposableLSPStateService.isServerShutdown()) return;
    String uri = params.getTextDocument().getUri();
    LOG.info(format("Document closing invoked on URI %s", uri));
    interruptAnalysis(uri);
    communications.publishDiagnostics(ImmutableMap.of(uri, Collections.emptyList()));
    communications.cancelProgressNotification(uri);
    docs.remove(uri);
    clearAnalysedFutureObject(uri);
  }
```

We shouldn't handle copybook close, but clean all related errors to the program. We can't use URI for that because the same copybook can be used by more than one program at the same time.

**Comment by lxpdd** [comment]
Also applied to ctrl+hover on the text document in the main program
