### ISSUE TITLE
Update the settings description

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-lsp-for-cobol#1511]
Platform: MacOs 12.4
VSCode: 1.70.2
Extension version: 1.0.2

There is a description listed for the setting: `cobol-lsp.cpy-manager.paths-local` says that the setting only supports **relative** paths, but it actually works with absolute paths too:

<img width="965" alt="Screenshot 2022-08-19 at 16 21 20" src="https://user-images.githubusercontent.com/74672982/185639422-b6034351-6e82-4adf-8770-972f3aa9d0af.png">

May I propose to update the description to avoid any misunderstanding in future?

**Comment by VitGottwald** [comment]
@zeibura , could you, please, take a look at this?
