### ISSUE TITLE
The REDEFINES clause must begin in Area B

### ISSUE THREAD

**Issue by zFernand0** [eclipse/che-che4z-lsp-for-cobol#1580]
Hello,
The VSCode parser indicates a problem when using the REPLACING clause with a REDEFINES on some copies.
The compilation is going well.

**To Reproduce**

add a copy to a program
add below the same copy with the REPLACING clause and the word REDEFINES in the target area

whatever the copy, the anomaly appears

**Screenshots**
![REDEFINES AREA B](https://user-images.githubusercontent.com/103997342/195886192-4cd31cbc-8013-467a-95c6-2aa15acfbc78.PNG)

**Desktop (please complete the following information):**

OS: Windows
Zowe Explorer Version: v2.3.0

_Originally posted by @ROBIN-Olivier in https://github.com/zowe/vscode-extension-for-zowe/issues/1975_

**Comment by VitGottwald** [comment]
Thank you for forwarding the bug report @zFernand0 . I managed to reproduce the scenario in https://github.com/VitGottwald/cobol-bug-1580 .

**Comment by zFernand0** [comment]
I might have redirected the issue to the wrong repository.
Please see:
- https://github.com/IBM/zopeneditor-about/issues/287

**Comment by ROBIN-Olivier** [comment]
Thank you !
