### ISSUE TITLE
COPY in column 7

### ISSUE THREAD

**Issue by ROBIN-Olivier** [eclipse/che-che4z-lsp-for-cobol#1581]
## Description ##
When I code a copy in column 1 to 6 of my cobol program, an anomaly message is displayed.
But when I code it in column 7, no anomaly is detected.
![PB Copy colonne 7](https://user-images.githubusercontent.com/103997342/196380201-494e2b88-1106-492b-8f28-7fcca8cdd1df.PNG)

However, the compilation crashes because the COPY is badly positioned.

**Comment by zimlu02** [comment]
Hi @ROBIN-Olivier,

as I mentioned in https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/1579#issuecomment-1282107790 you may be referring to a defect in extension from a different vendor. 
I suggest trying out the [latest version of COBOL Language Support](https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/development/lastSuccessfulBuild/artifact/cobol-language-support-1.0.2+development.1239.vsix) if it gives you a better results.
Thank you!
