### ISSUE TITLE
Formatting a COBOL source file ends up in discarding all the unsaved changes

### ISSUE THREAD

**Issue by roman-kupriyanov** [eclipse/che-che4z-lsp-for-cobol#1622]
## Description ##

When formatting capabilities (**Right click in editor -> Format document**) are used for any COBOL source file, every current unsaved change is reverted back to the last saved file state. This is especially problematic if is used in combination with **Format on Save** VSC setting, since all the changes are reverted on each file save attempt.

## Steps to reproduce ##

1. Open any COBOL source file (make sure that language for a document is autoselected properly to COBOL too or select it manually).
2. Try to make some changes to the file which are not related to the formatting itself (for example, to change variable name or something else meaningful) and without a single save (the file editor should show a "dirty" state with a "dot").
3. Right click anywhere in the document and select **Format Document**.
4. Notice how all the introduced changes are gone after formatting.

## Expected behavior ##

The changes which are not related to improper formatting should persist after the file formatting attempt.

## Screenshots ##

![changes-disappear](https://user-images.githubusercontent.com/91762867/202735397-f3bd7a77-674c-4372-bf6d-1d2b2ec02013.gif)

## Environment ##
 

OS: MacOS v13
IDE: VSCode v1.73.1
Extension: COBOL Language Support v1.1.0

## Additional information ##

Additionally have checked with COBOL LS disabled - no issues noticed.

**Comment by roman-kupriyanov** [comment]
Hi, I have just noticed another problem but this time with formatting of a change affecting the formatting itself:

![change-revert-2](https://user-images.githubusercontent.com/91762867/204017473-c026e8e6-62f5-4311-93a8-25c2f26ea4b6.gif)
###

**Comment by VitGottwald** [comment]
Hello @roman-kupriyanov, thank you for reporting this issue. It looks like the formatting implementation reads the source on disk rather than from the editor. We will take a look at this.

**Comment by roman-kupriyanov** [comment]
Retested with COBOL LS v1.1.1, the bug is gone now. Thank you for fixing it!

But it seems that formatting is not doing anything at all now (wrong formatting is not fixed and stayed as is after **Format document** is applied). Was this function disabled completely now?

**Comment by zimlu02** [comment]
Hi Roman,

as agreed this issue can be closed. We will continue with the following enhancements within #1623.
