### ISSUE TITLE
New copybooks are not recognized when empty

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#165]
## Description ##

When a new copybook (required inside a cobol file and marked as not found) is created, the syntax error doesn't disappear from the main cobol file until the copybook is not fulfilled with some content. 
## Steps to reproduce ##

1. Define a cobol file with a copybook that doesn't exists.
2. See the related semantic error "Copybook not found"
3. Create the required copybook under the COPYBOOKS folder
4. Switch back on the main cobol file
5. The semantic error is still present in the main cobol file
6. Try to add some content inside the copybook
7. Switch back again on the main cobol file
8. The related error now disappear.

## Expected behavior ##
The error for missing copybook should disappear when the file is created, even if it is empty.

## Screenshots ##

![gif that reproduce the issue](https://raw.githubusercontent.com/zacanbrcom/gifs/master/bug_watcher.gif)
## Environment ##
 

 - OS: [Windows 10]
 - IDE: [VS Code, Che 7, Theia IDE]

**Comment by temanbrcom** [comment]
Tested with the last development branch - reproduced when the copybook file is empty.
