### ISSUE TITLE
COBOL COPYBOOK: Syntax error on '<EOF>' expected {ID, IDENTIFICATION}

### ISSUE THREAD

**Issue by Kholtien** [eclipse/che-che4z-lsp-for-cobol#166]
Hey There,

I'll start by saying I'm not super familiar with Cobol but I am a sys admin for a legacy system that has thousands of cobol files (that don't typically need to be maintained, just read from time to time to figure out obscure issues). 

I've taken to reading the files in VS Code and came across this error. 

Syntax error on '<EOF>' expected {ID, IDENTIFICATION} 

The error highlights the very first character of most of the copybooks. In the copybook there are a bunch of comments and then the actual code part. The particular code I'm looking at for this particular copybook is only 22 lines long, basically 2 if statements then 

`      *
      ***  End of file.
      *`

**Comment by zacanbrcom** [comment]
Hello @Kholtien, thanks for your feedback.
At moment we don't support syntax and semantic analysis within a copybook file, and as discussed here #149 we'll introduce this support later on. The error message you got is caused by the issue that I mentioned. Btw if possible could you share your copybook to better understand the root cause of your syntax error?

**Comment by Kholtien** [comment]
Here's an example of one that we are using

`      ******************************************************************
      *                                                                *
      * Copyright (c) 2000, 2007, Oracle. All rights reserved.         *
      *                                                                *
      ******************************************************************
      *                                                                *
$#BSES* REVISION-INFO Start Exit, Do not modify - Dev. Only.
      *  $DateTime: 2007/07/03 10:31:19 $
      *  $File: //C1/2.2.0/Code/modules/c1/source/cobol/zz/CICZBTCI.cbl $
      *  $Revision: #1 $
$#BSEE* REVISION-INFO End Exit, Do not modify - Dev. Only.
      ******************************************************************
      *                                                                *
      * CICZBTCI - Copybook used in the initialize section of          * 
      *            batch drivers.                                      *
      *                                                                * 
      ******************************************************************

      *
      ***  Prepare the ZSTAT
      *

           INITIALIZE TRC-SYS-TIME OF ZSTAT
           SET STATUS-OK OF ZSTAT
               CONNECTION-BATCH OF ZSTAT
               APPLICATION-MESSAGE OF ZMSGN TO TRUE
               SW-NO OF IGNORE-WARNING-SW OF ZSTAT TO TRUE

           SET RETURN-CODE-OK TO TRUE

           SET ACTION-CONNECT OF ZSQLN TO TRUE

           MOVE PROGRAM-NAME OF W-LIT TO JOBID OF ZSTAT

      *
      ***  Connect to database
      *
           CALL 'CIPZSQLN' USING ZSQLN
                                 ZSTAT
                                 ZMSGN

           IF  RTNCD-ERROR OF ZSQLN
               MOVE  'CA000 DATABASE CONNECT'
                       TO  ERR-SECTION OF ZSQLN
               PERFORM  ZZ000-SQL-ERROR
           END-IF
      *
      ***  Get the scheduler id , if needed
      *
           IF  SCHEDULER-ID OF ZSQLN  =  ZEROS

               SET SEQ-NAME-SCHEDULER-ID OF SEQ-NAME OF ZRUND TO TRUE
               SET SW-YES OF ISSUE-COMMIT-SW OF ZRUND TO TRUE
               CALL  'CIPZRUND' USING  ZSQLN
                                       ZSTAT
                                       ZRUND
                                       ZMSGN

               IF  NOT  RTNCD-OK OF ZSQLN
                   SET SEVERITY-SEVERE OF ZMSGN
                       TO TRUE
                   MOVE ZERO TO PARM-COUNT OF ZMSGN
                   PERFORM ZM000-LOG-MESSAGE
                   PERFORM ZZ999-EXIT-PROGRAM
               END-IF

               MOVE SEQ-NUM OF OUTPUT-WRK OF ZRUND
                       TO SCHEDULER-ID OF ZSQLN
                          SCHEDULER-ID OF ZSTAT
           ELSE
               MOVE SCHEDULER-ID OF ZSQLN
                       TO  SCHEDULER-ID OF ZSTAT
           END-IF

      *
      ***  Get the current date and time
      *
           CALL  'CIPZDTTM' USING  ZSQLN
                                   ZSTAT
                                   ZDTTM
                                   ZMSGN

           MOVE SYS-DTTM OF ZDTTM TO PROCESS-DTTM OF ZSTAT
      *
`

**Comment by grianbrcom** [comment]
The fix for the error message is in pull request #203.
