### ISSUE TITLE
Introduce allowed list for accepted document types

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#173]
## Description ##
In Visual Studio Code when Git extension in enabled and the user open a new file, two ```didOpen ``` requests are sent to the server. For an example file called ```Test.cbl``` those two URIs are sent to the server:
1. **file:///c%3A/Users/user/cobol/ZCNCBL1.cbl**
2. **gitfs:/c%3A/Users/user/cobol/ZCNCBL1.cbl.git?path%3Dc%253A%255CUsers%255Cuser%255Ccobol%255CZCNCBL1.cbl%26ref%3D**

There is also a similar issue on VSC repository closed as ''expected behavior'' available here: https://github.com/microsoft/vscode/issues/89605.
This behavior is not experienced on Che/Theia.
This bugfix will provide to the user a notification message that the gitfs is not supported.

## Steps to reproduce ##

1. Open Visual Studio Code and check that the git extension is enabled and Cobol Language Support is installed from the Marketplace.
2. Open a file under version control.
3. An error message is shown to the user **The given document extension in unsupported: cbl%26ref%3D**
## Expected behavior ##

An error message should explain the user that the gitfs uri is not supported by the Cobol Language Support.
Or is possible investigate to found a way to discard immediately any incoming ```didOpen``` request with unsupported file type (implementing a check on Cobol Language Support extension or on the server).
## Screenshots ##

![image](https://user-images.githubusercontent.com/48674737/73663434-daa0c300-469d-11ea-9761-cdeaf8508f54.png)

**Comment by dankox** [comment]
It would be nice, if you could turn off or disable this notification introduced in #192 .

Opening multiple files in succession spawn multiple notification boxes in vscode, which doesn't give user any useful information (as it doesn't affect user's work with cobol files). 
Probably might be fixed in the vscode extension rather than in LSP, so this notification could be suppressed in vscode while LSP gives relevant response. But regardless where it could be fixed, it would be nice to have suppress option :)

**Comment by zimlu02** [comment]
> It would be nice, if you could turn off or disable this notification introduced in #192 .
> 
> Opening multiple files in succession spawn multiple notification boxes in vscode, which doesn't give user any useful information (as it doesn't affect user's work with cobol files).
> Probably might be fixed in the vscode extension rather than in LSP, so this notification could be suppressed in vscode while LSP gives relevant response. But regardless where it could be fixed, it would be nice to have suppress option :)

Hi Danko, you're right. We will move the notification into the 'Problems' console.

**Comment by dankox** [comment]
Great... that's even better option 👍
