### ISSUE TITLE
Dependency file should contain 8 char max copybook name

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#175]
## Description ##
There is a limit of 8 characters per member name on mainframe.
The dependency file that holds the list of missing copybooks should truncate the copybook name to 8 chars only so that the rest call to retrieve the member won't fail.

Note:
This implementation may change in the future, once support for USS is added.

## Acceptance Criteria ##
- In the dependency file the name is truncated to max 8 chars long

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

**Comment by Morridt** [comment]
Hi all. My issue with this is that 30 years ago my company decided to use Panvalet and make full use of the increased file name. So we have many copybooks (10s thousands) with 10 char file names that we include via ++INCLUDE (refer earlier CR) . We can get these copybooks from USS (plan to replicate them from Endevor) and also via PDS if we renamed along the way to download it locally.

**Comment by temanbrcom** [comment]
Hello @Morridt, 
Thank you for your comment! Panvalet syntax is not supported at the moment. We will keep in mind the use case you've mentioned.

**Comment by ishche** [comment]
@temanbrcom Does it make sense to create an issue for this case?

**Comment by zimlu02** [comment]
Hi @Morridt, 
thank you for your feedback. Support for Panvalet and USS is already on our internal roadmap. We want to get the users' feedback on current implementation first before we will define other enhancements though.
