### ISSUE TITLE
Dependency files should be created/updated when document is open or using code action

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#196]
## Description ##

In order to prevent unexpected issue when autosave option is enabled, the dependency file for missing copybooks should be created and updated only in two conditions:
- the document is open in the editor and there is a copy instruction
- after the triggering from the code action

## Steps to reproduce ##
1. Verify that autosave is enabled
2. Open a cobol file
3. Start to write copy instruction taking few second of delay for each letter of the copybook name
4. Bunch of items in the dependency file will be created (one for each letter written)

## Expected behavior ##

The depfile should contain the full name of the copybook, adding each character as different copybook lead in issues and unexpected behavior.
 
### Inside the cobol file... ###
```
// other stuff
COPY ABCDEF.
// other stuff
```
### Dependency file create for the Cobol file: ###

```
A
AB
ABC
ABCD
ABCDE
ABCDEF
```

## Additional information ##

Is necessary double check the expected behavior so in that case a question tag is added.

## Technical notes ##
Update unit tests:
- [x] ```FileSystemE2ETest```
- [x] ```CobolLanguageEngineTest```
- [x] ```CobolCleanExtraLanguageTest```
- [x] ```CobolVariableCheckTest```
- [x] ```DocumentExtensionTests``` //double check later
- [x] ```MyTextDocumentServiceTest```
- [x] ```AnalyzeCopybookCaching```

**Comment by temanbrcom** [comment]
Connected with #197
