### ISSUE TITLE
Introduce Dependency Injection

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#24]
# Description
As a software engineer, I would like to have a dependency injection support so I can build the dependencies between the components in an easy way. 

# Acceptance criteria

- [x] TPSR is verified

- [x] DI is configured for the service and core parts

- [ ] DI is applied to the current dependencies 

- [x] The solution is tested on all the platforms

- [x] Licence information is updated

# Technical notes
As a software engineer, I would like to have a lightweight DI framework, not some enterprise-level one. Have a look at [Guice](https://github.com/google/guice).

**Comment by shciubrcom** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19101
Guice 4.2.2 has Type_B approval, we can use it.
