### ISSUE TITLE
Profile settings to be provided to LSP

### ISSUE THREAD

**Issue by sergiuilie** [eclipse/che-che4z-lsp-for-cobol#247]
## Description ##
When the profile is not defined in the settings.json, LSP server doesn't recognize the .copybook path specific to an open file because the path is created using the profile and the copybooks present in the .copybooks folder are not analyze and the diagnostic error is persistent in the file.

## Steps to reproduce ##
1. Open Zowe Explorer and do not fill any profile in settings.json (User or Workspace)
2. Open a COBOL file
3. Download the copybooks by providing only the path to them

## Expected behavior ##
Profile settings to be provided to LSP

**Comment by ishche** [comment]
I suggest using a reversed approach. Let LSP ask for missing data by configuration request.

**Comment by sergiuilie** [comment]
> I suggest using a reversed approach. Let LSP ask for missing data by configuration request.

why not?

**Comment by zacanbrcom** [comment]
INHO LSP shouldn't be triggered by the user but the client extension should fulfill it correctly
