### ISSUE TITLE
Dependency File is not created/update when modify cobol file using zowe on Che

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#259]
## Description ##

The dependency folder and its content is sometimes not created/updated in the scenario when the user will use zowe explorer to open the cobol file.
This problem is actually visible only on Che enviroment using zowe explorer and this need a verification about the triggering of ```DID_OPEN``` event when the cobol file is loaded in the editor, and plan the appropriate fix on LSP side or file an issue to the responsible component.

## Steps to reproduce ##

1. Delete existent .cobdeps folder and its content
2. Open a cobol file using zowe explorer
3. Sometimes the cobdeps folder is not created and/or the dependency file inside is not created/updated.
## Expected behavior ##

The dependency folder and its content should be every time created and updated
## Environment ##
OS: [ALL]
IDE: [Eclipse Che]

**Comment by sergiuilie** [comment]
It is opposite, Theia IDE doesn't trigger the `DID_CLOSE` event so this leads to `DID_OPEN` to not be called.
I was searching for an issue in [eclipse-theia](https://github.com/eclipse-theia/theia/issues) project and I found nothing about this, I think this issue should be created in that project.
