### ISSUE TITLE
Introduce the support to Powermock

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#262]
## Description ##
Since Mockito lacks to support private methods, the addition of Powermock will have impact on the already defined unit test, the following classes may be updated when Powermock will be available on development branch:
- [ ] ```MyTextDocumentService#getDocs()```
- [ ] ```CopybookDependencyServiceImpl#isFileInDidOpen()```

## Acceptance Criteria ##
- Unit test suite works correctly.
- No production code is damaged and no regression about functionality currently supported.

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

## Technical details ##
This is the place for any implementation-related notes

**Comment by temanbrcom** [comment]
Outdated
