### ISSUE TITLE
Split lexer grammar

### ISSUE THREAD

**Issue by sergiuilie** [eclipse/che-che4z-lsp-for-cobol#264]
## Description ##
Refactor the main grammar in order to split the language-specific parts (i.e. COBOL, CICS, and SQL) and technical rules. Should be applied to both parts - lexers and parsers. 

## Acceptance Criteria ##
- Extracted lexer and parser for technical tokens to be a common part of the language-specific grammars
- No duplications in lexer files
- Technical grammar is available for all the languages

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

## Technical details ##
This is the place for any implementation-related notes

**Comment by asatklichov** [comment]
Lexer grammmars are now like: CommonCobolLexer, Db2SqlLexer, CICSLexer and CobolLexer
