### ISSUE TITLE
MF dataset missing, pop-up in a loop

### ISSUE THREAD

**Issue by sergiuilie** [eclipse/che-che4z-lsp-for-cobol#269]
## Description ##
If a non-existing dataset is specified in `settings.json` paths configuration than a pop-up message showing `Can't read member <dataset path>` keep popping up.

## Steps to reproduce ##
1. Go to settings.json and provide a non-existing dataset
2. Click on download copybooks
3. See error.

## Expected behavior ##
Pop-up message to be triggered when a new download was requested or just one time.

## Screenshots ##
![image](https://user-images.githubusercontent.com/23320888/78574602-7da2c400-782a-11ea-9dcd-b38736f0acfe.png)

## Environment ##
 - OS: Windows 10
 - IDE: VSCode

**Comment by grianbrcom** [comment]
Let me investigate it.

**Comment by grianbrcom** [comment]
Right now if you have nonexisting dataset specified. But all copybooks are resolved - no errors at all. Otherwise, you will see:
![image](https://user-images.githubusercontent.com/60617592/150153181-148f44b4-5d60-4cff-86dd-aaa75240e250.png)
At least the error message appears once.
