### ISSUE TITLE
Incorrect Error Position Underlining

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#27]
## Description
I have a definition of variables:

```
01 VISATOTAL2.
     02 PRNVISATOTAL.
          03 ABC.
             04 DEF.
                 05 HGI.
```

When I call HGI as in the image:
![ERRORPOSITION](https://user-images.githubusercontent.com/47776865/65309859-3c4c0f00-db8d-11e9-8579-b60ac523679e.PNG)

### Actual behavior:
"HGI of DEF" is underlined

### Expected behavior:
The error should be shown on VISATOTAL, one line after the call of HGI.

**Comment by zacanbrcom** [comment]
![ISSUE_21](https://user-images.githubusercontent.com/48674737/65327557-8f858800-dbb4-11e9-8776-7d40b2c1e6f8.PNG)

> Seems not reproducible, I will close it for now and I will reopen it again in case.
