### ISSUE TITLE
Grammar throws an error when adding a hyphen to the end or start of a copybook name

### ISSUE THREAD

**Issue by abdrabrcom** [eclipse/che-che4z-lsp-for-cobol#272]
## Steps to reproduce ##
1. add a hyphen '-' to the end or start of a copybook name

## Expected behavior ##
Grammar should not throw an error

## Screenshots ##
![image](https://user-images.githubusercontent.com/52322307/78785246-13635e00-79a7-11ea-89a8-286be3441f86.png)

## Environment ##
 - OS: Windows 10 version 1903
 - IDE:  VS Code v. 1.43.2

**Comment by sergiuilie** [comment]
This is the expected behavior and it is working as per COBOL [documentation](https://www.ibm.com/support/knowledgecenter/en/SS6SG3_6.2.0/lr/ref/rlcdscop.html).  I am closing this issue.
