### ISSUE TITLE
Broadcom Folder in my VSCode Workspace

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#307]
**Is your feature request related to a problem?**
I am using the VSCode ext in my machine. And whenever I use this extension, there are folders added in my workspace when I open my COBOL program.

![Capture](https://user-images.githubusercontent.com/45042840/79963692-fdb36580-8489-11ea-99d1-fb4127cd55ec.PNG)

**Describe the solution you'd like**
 I don't know why I need to see this. Can it be transferred to another location? I have to add it in my gitignore all the time and it is annoying.

**Describe alternatives you've considered**

**Additional information**

**Comment by temanbrcom** [comment]
Hello @jellypuno 
Could you, please, attach one of these zip archives? 
Thank you!

**Comment by jellypuno** [comment]
[app.2020-04-20.0.log.zip](https://github.com/eclipse/che-che4z-lsp-for-cobol/files/4515484/app.2020-04-20.0.log.zip)

**Comment by temanbrcom** [comment]
What OS do you use?

**Comment by jellypuno** [comment]
Windows 10

**Comment by temanbrcom** [comment]
I've checked this and found an incorrect log path pattern. I'll fix it.
Thank you for this issue!
