### ISSUE TITLE
Informational Message: No Syntax Error

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#308]
**Is your feature request related to a problem?**
Currently, If I open a Cobol program an informational message appears telling that there is no syntax error.

**Describe the solution you'd like**
If there are no syntax error, is it possible to **not** inform me about it? If I am trying to check multiple programs, this message appears multiple times as well. 

![Capture](https://user-images.githubusercontent.com/45042840/79964385-ec1e8d80-848a-11ea-994c-2ed759383315.PNG)

**Describe alternatives you've considered**
You can inform me only if there is an error in my program.

**Additional information**

**Comment by temanbrcom** [comment]
We discussed this issue and decided to replace showing a pop-up with console logging as it is described here #312
