### ISSUE TITLE
LSP Client with Zowe Secure Store

### ISSUE THREAD

**Issue by sergiuilie** [eclipse/che-che4z-lsp-for-cobol#317]
## Description ##
Zowe is using the Secure Store in order to store user credentials. Our client is depending on that credentials at download copybooks from the PDS moment but we can not retrieve any credentials.

## Steps to reproduce ##
1. Use latest version of Zowe Explorer and add credentials using Secure Store
2. Open a COBOL file which contains copybooks ready to be downloaded from MF
3. See the error that keeps popping up 

## Expected behavior ##
LSP Client is working with Secure Store

**Comment by BartS07** [comment]
Experienced same issue. Copybooks will only be retrieved when the Zowe CLI z/OSMF profile is stored unsecure.  When stored secure with secure-credential-store we get errors like:
Invalid credentials for profile: <profilename>. Copybook retrieval is blocked. Ensure the profile contains correct credentials.

**Comment by zimlu02** [comment]
Fixed by:
https://github.com/eclipse/che-che4z-lsp-for-cobol/pull/1202
