### ISSUE TITLE
Dataset path case insensitive

### ISSUE THREAD

**Issue by sergiuilie** [eclipse/che-che4z-lsp-for-cobol#323]
## Description ##
Dataset path in `settings.json` should be case insensitive.

## Steps to reproduce ##
1. Go to `settings.json` and set a dataset path using upper case characters
2. Download one copybook which stays into that dataset by opening a COBOL program which invokes that specific copybook
3. Go to `settings.json` and set the same dataset path using lower case characters and delete the upper case path
4. Open another COBOL program which contains the same copybook invocation and download it
5. See that there are 2 directories created with the same path differentiated by lower/upper case

## Expected behavior ##
Make sure that the dataset path in `settings.json` will be interpreted case insensitive.

## Screenshots ##
![image](https://user-images.githubusercontent.com/23320888/80492925-f6e29200-8964-11ea-951a-0e0f21297b5f.png)

## Environment ##
 - IDE: [Che 7.9, Theia IDE]

**Comment by grianbrcom** [comment]
I still can reproduce it:
![image](https://user-images.githubusercontent.com/60617592/150154914-07f35791-fb15-40f0-bcd7-f943a217010d.png)

**Comment by zimlu02** [comment]
Works on supported IDEs (VSC, GitHub Codespaces).
