### ISSUE TITLE
Remove unit test logging from log file

### ISSUE THREAD

**Issue by zacanbrcom** [eclipse/che-che4z-lsp-for-cobol#324]
## Description ##

Log file is intended to host useful information regarding problem that occur when the user perform action using the Cobol Language Support.
Logging of unit tests give no value to the end user and shouldn't be written in the log file.

## Additional information ##

Could be useful have a look to the logback configuration for test class and be sure that no file appender are defined but only throw logs on the console.

**Comment by temanbrcom** [comment]
We don't run unit tests on the end user's side, do we?

**Comment by zacanbrcom** [comment]
No we don't but in any case we should avoid to write on flat file exception for tests
