### ISSUE TITLE
Stack trace is dumped on the screen while typing COBOL code.

### ISSUE THREAD

**Issue by tJ3l33s** [eclipse/che-che4z-lsp-for-cobol#380]
## Description ##
Stack trace is dumped on the screen while typing COBOL code.

## Steps to reproduce ##
This problem happens intermittently. 

## Screenshots ##
![image](https://user-images.githubusercontent.com/64498041/83954594-a2122100-a818-11ea-8f54-ae316e84821f.png)

## Environment ##
As copied from VS Code Help | About:
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

## Additional information ##
This issue was opened per advice in the Open Mainframe Project cobol-programming-course channel.

Regards, Peter

**Comment by temanbrcom** [comment]
Hello @tJ3l33s,

Thank you for this report!
It seems a little strange, what version of the COBOL plugin do you use?

**Comment by tJ3l33s** [comment]
Hello Andrei,

Thank you for your e-mail.  Below is a screen snapshot of all extensions installed as of this morning.  That is not to say the same versions were installed at the time of the incident.  Is there anything else I can supply you, should the stack trace happen again?

Regards, Peter
![image](https://user-images.githubusercontent.com/64498041/84034349-363ece00-a968-11ea-9fa6-7e930f15f706.png)

**Comment by temanbrcom** [comment]
Thank you, Peter!
Looking at the package names in the stack trace, I may say that it is thrown by IBM Z Open Editor. Could you, please, try to switch it off and try to reproduce this behavior with only COBOL Language Support enabled?

Kind regards,
Andrei Temnikov

![image](https://user-images.githubusercontent.com/47776865/84035632-54bebc80-a99c-11ea-8435-aa606cea0b96.png)

**Comment by tJ3l33s** [comment]
Hello Andrei,

Yes, I can try that.  I'm not sure of the exact sequence of events to trigger the incident.  I believe I was typing a new paragraph name at the time, but I've type dozens of paragraph names since then, and there were no issues.  I'd categorize this matter as an intermittent nuisance.  I'll do what I can to track it down.

Regards, Peter

**Comment by tJ3l33s** [comment]
Hello Andrei,

I see @zeibura closed this bug.  Can you share with me what issues were resolved, please?  Can I enable the IBM Z Open Editor again?

Regards, Peter

**Comment by tJ3l33s** [comment]
> Hello Andrei,
> 
> Yes, I can try that. I'm not sure of the exact sequence of events to trigger the incident. I believe I was typing a new paragraph name at the time, but I've type dozens of paragraph names since then, and there were no issues. I'd categorize this matter as an intermittent nuisance. I'll do what I can to track it down.
> 
> Regards, Peter

Hello Andrei,

I see @zeibura closed this bug. Can you share with me what issues were resolved, please? Can I enable the IBM Z Open Editor again?

Regards, Peter

**Comment by temanbrcom** [comment]
Hello Peter,

The most likely that this problem is on IBM Z Open Editor side, and is not a plugin compatibility issue. 
I could not reproduce it on my side. Maybe, it was fixed in the latest Open Editor releases. 
This fix was about adding a precaution to the readme that the user might see some unexpected behavior using several COBOL plugins simultaneously.
You may enable the plugin again, update, and try to reproduce the issue. If you see it again, then, please, add a bug report here: https://github.com/IBM/zopeneditor-about/issues
Thank you!

Kind regards,
Andrei Temnikov
