### ISSUE TITLE
Peek reference does not work correctly with continuation line

### ISSUE THREAD

**Issue by grianbrcom** [eclipse/che-che4z-lsp-for-cobol#413]
## Description ##

The statement on a continuation line showed on the previous line when the user tries to peek reference.

## Steps to reproduce ##

1. Open VSCode or Theia with an installed extension (Bitlang extension must be deactivated).
1. Create a .cbl file that will contain the following piece of code:
```
       Identification Division.
       Program-id. HELLO-WORLD.
       Data Division.
       Working-Storage Section.
           05 User-City PIC X(5).
       Procedure Division.
        100-Print-User.
           Move 'Prague' 
      -       To User-City.
       End program HELLO-WORLD
```
1. Peek references of `User-City`
1. The reference showed on the line `Move 'Prague' `

## Expected behavior ##

The line with `To User-City.` must be highlighted.

## Screenshots ##

![image](https://user-images.githubusercontent.com/60617592/86381040-21b2d480-bc8d-11ea-8e0a-d7fec32a061f.png)

## Environment ##
 
OS: Linux
IDE: VS Code

## Additional information ##

In the preprocessing stage in Java code, the plugin merge continuation lines into one line.

**Comment by temanbrcom** [comment]
May be helpful https://stackoverflow.com/questions/18782388/antlr4-lexer-error-reporting-length-of-offending-characters
