### ISSUE TITLE
Rename all fe test files to *.spec.ts

### ISSUE THREAD

**Issue by asatklichov** [eclipse/che-che4z-lsp-for-cobol#429]
## Description ##
As a SE, I would like to see front-end test files with spec suffix.  It helps (*.spec.ts)  to show them as test icon in vscode and is more of an industry standard. 

## Acceptance Criteria ##
No single regression issue expected.    
Test files shown with test icon in vscode  

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

## Technical details ##
This is the place for any implementation-related notes

**Comment by ishche** [comment]
Isn't it `*.test.ts` for jest framework?
AFAIK `*.spec.ts` is standard for angular.

**Comment by asatklichov** [comment]
> Isn't it `*.test.ts` for jest framework?
> AFAIK `*.spec.ts` is standard for angular.

@ishche 
Jest supports both[ by default](https://jestjs.io/docs/en/configuration#testmatch-arraystring), and spec is more general.

**Comment by ishche** [comment]
> @ishche
> Jest supports both[ by default](https://jestjs.io/docs/en/configuration#testmatch-arraystring), and spec is more general.

Jest also supports angular.
but we don't have angular in this project.
I want to avoid confusion on that point. That's why I suggest using `*.test.ts` convention as jest does in the documentation.

**Comment by asatklichov** [comment]
> > @ishche
> > Jest supports both[ by default](https://jestjs.io/docs/en/configuration#testmatch-arraystring), and spec is more general.
> 
> Jest also supports angular.
> but we don't have angular in this project.
> I want to avoid confusion on that point. That's why I suggest using `*.test.ts` convention as jest does in the documentation.

Spec is not Angular specific, e.g. Jest used in React with spec.js, [here ](https://www.valentinog.com/blog/testing-react/)
