### ISSUE TITLE
Unifying multiple Java modules into one project

### ISSUE THREAD

**Issue by asatklichov** [eclipse/che-che4z-lsp-for-cobol#431]
## Description ##
 
As a SE I want to have all Java modules with one unified name under the project.  
Reason is these modules are not independently used or deployed as a separate project. All modules  belong to one projects. 

## Acceptance Criteria ##
- all modules will be unified under one project   
- application should fully support all the existing features provided by lsp-server. No single regression issue expected.  

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

## Technical details ##
This is the place for any implementation-related notes

**Comment by zacanbrcom** [comment]
Closed by #473
