### ISSUE TITLE
Syntax Highlighting is not working

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#449]
## Description ##
Syntax Highlighting is not working. 
Note: I uninstalled COBOL Bitlang and Installed COBOL LSP and COBOL Control Flow

## Steps to reproduce ##
1. Open a large COBOL file (38k lines) with *.cbl extension and COBOL as language mode
2. Wait for the Syntax check to finish.
3. The errors from the syntax check will appear but the highlighting is still not there.

## Environment ##
Windows 10
VSCode

## Additional information ##
COBOL LSP de-activates when I try to install COBOL Bitlang for highlighting

**Comment by zimlu02** [comment]
Hi Jelly, the syntax coloring will be released in next version 0.13.0. 
Deactivation of the plugin is probably a new feature of the latest Bitlang version.

**Comment by jellypuno** [comment]
I see. Thank you for the update. I will close this issue
