### ISSUE TITLE
Support for CICS statements (basic intellisense) 

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-lsp-for-cobol#469]
As a user, I want to have a basic version of IntelliSense implemented within COBOL LSP  to improve performance and quality of work when working with a COBOL file containing CICS statements in any IDE supporting LSP.

**Acceptance Criteria:**

- [x] highlighting of CICS statements is supported (if LSP provide support for coloring)

- [x] syntax check of CICS statements is supported

- [x] fix and create unit tests for the new feature

- [x] autocomplete(content assist) of CICS statements for basic CICS keywords is supported

- [x] there is no clash with the current implementation of COBOL IntelliSense

**Comment by zacanbrcom** [comment]
Finish the manual testing, below the result:

- [x] highlighting of CICS statements is supported (if LSP provide support for coloring)
- [x] syntax check of CICS statements is supported
- [x] autocomplete(content assist) of CICS statements for basic CICS keywords is supported
- [x] there is no clash with the current implementation of COBOL IntelliSense

Snippet that I used:
```
EXEC CICS HANDLE AID PA1(LAB1)
     ANYKEY(LAB2) PF10
END-EXEC  
```
We also support the ```DFHAID``` copybook defined in the data division, here the reference to that standard copybook: https://www.tutorialspoint.com/cics/cics_aid_keys.htm
