### ISSUE TITLE
Consider changing level definition syntax analysis to visitor instead of lexer

### ISSUE THREAD

**Issue by sergiuilie** [eclipse/che-che4z-lsp-for-cobol#482]
## Description ##
In order to eliminate some ambiguity in `integerLiterals` rule, I suggest to analyze and discuss the possibility to move the syntax analysis check to the visitor or use semantic predicates directly in .g4 file

## Acceptance Criteria ##
- AC #1 Refactor rule to reduce ambiguity
- AC #2 Testing

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing is done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

**Comment by temanbrcom** [comment]
I made a small research on how to implement syntax analysis on the visitor, and it seems that it has not enough context to apply some checks. E.g. it cannot apply lookahead, so it will be impossible to find a missing or unwanted token

**Comment by sergiuilie** [comment]
True, my idea is focusing purely on this rule because we have logic using `otherLevel` and we can simply check it in visitor if its compliance with wanted behavior.

**Comment by temanbrcom** [comment]
Implicitly fixed by changing the order of the `cicsWord` subrules
