### ISSUE TITLE
Variable Usage Cannot Be Found for Variable Name Adjacent to a String Literal

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#548]
## Description ##

If there is no whitespace between a variable and a string literal in a DISPLAY statement, then "Go to Definition" won't work for this variable usage.

## Steps to reproduce ##
1. Open a COBOL file
2. Add a variable definition for `VARNAME`.
3. Add `DISPLAY "smth "VARNAME.` in the `PROCEDURE DIVISION`
4. Call "Go to Definition" on `VARNAME`
5. See "No definition found" message

## Expected behavior ##
"Go to Definition" works as expected

## Screenshots ##

![image](https://user-images.githubusercontent.com/47776865/95354128-5e155280-08c4-11eb-9872-e305c1e05284.png)

## Environment ##
 - OS: All
 - IDE: All

## Additional information ##

The most likely the problem is with extracting a text token under the cursor in `MyDocumentModel`

**Comment by grianbrcom** [comment]
Fixed by #713
