### ISSUE TITLE
Prerequisite Java 11 disqualifies the solution

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-lsp-for-cobol#565]
**Is your feature request related to a problem?**

The use of the "Cobol Language Support" extension requires the Java version 11 runtime.

For licensing reasons, our company refuses the installation of a Java version greater than or equal to 1.8 build 201.
Use of OpenJDK has not been qualified and may not provide the same level of service as Java Oracle.

This disqualifies the use of the extension, or any other extension which would have as a prerequisite a Java version greater than or equal to 1.8 build 201.

Our current Java version is: 
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by zimlu02** [comment]
> **Is your feature request related to a problem?**
> 
> The use of the "Cobol Language Support" extension requires the Java version 11 runtime.
> 
> For licensing reasons, our company refuses the installation of a Java version greater than or equal to 1.8 build 201.
> Use of OpenJDK has not been qualified and may not provide the same level of service as Java Oracle.
> 
> This disqualifies the use of the extension, or any other extension which would have as a prerequisite a Java version greater than or equal to 1.8 build 201.
> 
> Our current Java version is:
> 
> ```
> java version "1.8.0_102"
> Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
> ```

Hi Denis,

we are actually considering embedding openJDK into our plugin. But my understanding is that this would not work for you either, correct?
Have you considered using Code4z within the Eclipse Che? The COBOL Language Support extension is a default part of the latest Eclipse Che instance and there is no dependency on JAVA whatsoever. 

Lukas
