### ISSUE TITLE
LSP COBOL doesn't retrieve the copybook from the mainframe.

### ISSUE THREAD

**Issue by jagbr01** [eclipse/che-che4z-lsp-for-cobol#566]
## Description ##

While working with Azat Satkichov we were able to issue the go to definition for a local copybook but if the copybook was on the mainframe it couldn't find it.  

{
    "broadcom-cobol-lsp.cpy-manager.profiles": "zowe-p2",
    "broadcom-cobol-lsp.cpy-manager.paths-dsn": ["JAGBR01.COPYBOOK.LIB"],
    "broadcom-cobol-lsp.cpy-manager.paths-local": ["copybooks"],
}

![image](https://user-images.githubusercontent.com/46793378/96586595-36a08b80-12af-11eb-896c-07b0f177f007.png)

## Expected behavior ##

Open the copybook.
## Screenshots ##

![image](https://user-images.githubusercontent.com/46793378/96586666-4e780f80-12af-11eb-844c-d1cd0ab40e59.png)

**Comment by temanbrcom** [comment]
I see the Outline is not shown here, so the analysis was not finished. I assume the COPY statement corrupts the document structure the way it cannot be processed. I will try to reproduce it at my side.

**Comment by temanbrcom** [comment]
I reviewed the analysis process and found one possible reason it would fail without any notifications: the attempt to resolve a locally defined copybook. Could you, please, copy here the full path to the copybook folder from the system explorer, and the path to the failing copybook after you resolve it manually

**Comment by jellypuno** [comment]
I have the same error:

![image](https://user-images.githubusercontent.com/45042840/96705302-61fda600-1395-11eb-8869-caad4a34bcf4.png)

This my settings:

```
    "broadcom-cobol-lsp.cpy-manager.paths-local": [
        "C:\\Users\\jp669971\\Documents\\GitHub\\Community\\Cobol-Made-Easy\\Copybooks"
    ],
    "broadcom-cobol-lsp.cpy-manager.paths-dsn": [
        "Z80428.COPY"
    ],
    "broadcom-cobol-lsp.cpy-manager.profiles": "zcobol",
```

I am not sure why it is saying invalid credentials, I was able to dowload and view my COBOL program via Zowe Explorer. There are no issues with my credentials

**Comment by temanbrcom** [comment]
Hi @jellypuno,
COBOL LS requires a relative path to the local copybooks, so probably you need to specify only "Copybooks" in your `broadcom-cobol-lsp.cpy-manager.paths-local`. Try to set it, restart your VS Code, and check if this error message appears again.
Thank you!

**Comment by jellypuno** [comment]
That works! thanks @temanbrcom . I kind of wish that the relative path info is also in the settings description. It says local path and I just assumed that I should copy the whole path.

**Comment by temanbrcom** [comment]
Good notice, we will discuss it. 
Thank you!
