### ISSUE TITLE
Retreiving IDEAL code source

### ISSUE THREAD

**Issue by khalid-lemghari** [eclipse/che-che4z-lsp-for-cobol#572]
Hello,

I don't know if che4z can retreive IDEAL code source ? To be controled with git, and versionned with CA Endevor.

Best regards,

**Comment by davsc01** [comment]
Hello

We don’t have that functionality in Code4z. However Broadcom has an option to Endevor that may address your needs. Please email me at Scott.davidson@broadcom.com and I’ll set up a meeting to discuss this further. 

Scott

**Comment by ishche** [comment]
No action is required here.
