### ISSUE TITLE
Continuation Lines Not Concatenated with an Empty Line in Between

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#619]
## Description ##

The continuation line should be concatenated with the previous unclosed string literal. If there is an empty line between the line and the literal, the are concatenated 

## Steps to reproduce ##
1. Open a COBOL file
2. Create a string literal with a continuation line split by an empty line
3. See error.

## Expected behavior ##

No syntax errors are shown.

## Screenshots ##

![image](https://user-images.githubusercontent.com/47776865/98252350-1b55a180-1f7a-11eb-8f55-b58013f5f136.png)

## Environment ##
 - OS: All
 - IDE: All

**Comment by ap891843** [comment]
I am planning to work on this issue.
