### ISSUE TITLE
LocalCopybookResolverTest fails randomly 

### ISSUE THREAD

**Issue by asatklichov** [eclipse/che-che4z-lsp-for-cobol#626]
## Description ##
Currently during the Jenkins build, sometimes LocalCopybookResolverTest fails. 
Error message: test parse method with correct setting configuration › parse a setting file with key 'LOCAL' return the values in an array

 
## Acceptance Criteria ##
- No regression issue 
- No failing test

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

## Technical details ##
LocalCopybookResolverTest
```

10:00:07      expect(received).toBe(expected) // Object.is equality
10:00:07  
10:00:07      Expected: 1
10:00:07      Received: 0
10:00:07  
10:00:07        132 | 
10:00:07        133 | function assertParseOf(value: any, expectedSizeList: number) {
10:00:07      > 134 |     expect(resolveCopybooksFromJSON(JSON.stringify(value)).length).toBe(expectedSizeList);
10:00:07            |                                                                    ^
10:00:07        135 | }
10:00:07        136 | 
10:00:07        137 | function assertResourceContent(list: string[], expectedSizeList: number) {
10:00:07  
10:00:07        at assertParseOf (src/__tests__/LocalCopybookResolverTest.spec.ts:134:68)
10:00:07        at Object.<anonymous> (src/__tests__/LocalCopybookResolverTest.spec.ts:56:9)
```

**Comment by ap891843** [comment]
Adding below log for one more intermittently failing test(UI)

> 10:10:06    ● LanguageClientService negative scenario. › LSP port not defined and jar path doesn't exists
10:10:06  
10:10:06      : Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error:
10:10:06  
10:10:06        56 | describe("LanguageClientService negative scenario.", () => {
10:10:06        57 | 
10:10:06      > 58 |     test("LSP port not defined and jar path doesn't exists", async () => {
10:10:06           |     ^
10:10:06        59 |         await expect(new LanguageClientService(undefined).checkPrerequisites())
10:10:06        60 |         .rejects.toThrowError("LSP server for COBOL not found");
10:10:06        61 | }, 10000);
10:10:06  
10:10:06        at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
10:10:06        at Suite.<anonymous> (src/__tests__/LanguageClientServiceTest.spec.ts:58:5)
10:10:06        at Object.<anonymous> (src/__tests__/LanguageClientServiceTest.spec.ts:56:1)

**Comment by ap891843** [comment]
This BUG is under observation. A change went in.

**Comment by temanbrcom** [comment]
No fails detected, the issue may be closed.
