### ISSUE TITLE
Support Completion for Locally Present Files

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#651]
**Is your feature request related to a problem?**

Completion request works only with copybooks and subroutines that were used in the current document. It would be nice if it shows also locally presenting ones.

**Describe the solution you'd like**

Provide an ability to scan the copybook and subroutine folders to list the files. Provide them on request. Invalidate cache on file deletion/creation.

**Additional information**

May require additional endpoints for the specific requests.

**Comment by grianbrcom** [comment]
Duplication of #106
