### ISSUE TITLE
MAPFAIL Produces a Semantic Error in HANDLE CONDITION

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#668]
## Description ##

The `MAPFAIL` exception condition produces a semantic error in `EXEC CICS`

## Steps to reproduce ##
1. Open a COBOL file
2. Add `EXEC CICS IGNORE CONDITION MAPFAIL END-EXEC.`
3. Add `EXEC CICS HANDLE CONDITION MAPFAIL(PARNAME) END-EXEC.` where PARNAME is a paragraph name
4. See a semantic error on MAPFAIL in both cases

## Expected behavior ##

No errors are shown.

## Environment ##
 - OS: All
 - IDE: All

## Additional information ##

https://www.ibm.com/support/knowledgecenter/SSGMCP_5.6.0/applications/designing/dfhp31o.html

**Comment by grianbrcom** [comment]
I can fix it.
