### ISSUE TITLE
HANDLE AID CLEAR() Produces a Syntax Error in EXEC CICS

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#670]
## Description ##

A `HANDLE AID CLEAR()` shows a syntax error on parenthesis when it should allow a blank value.

## Steps to reproduce ##
1. Open a COBOL file
2. Add `EXEC CICS HANDLE AID CLEAR() END-EXEC.`
3. See an error on the parenthesis

## Expected behavior ##

No syntax errors are shown.

## Environment ##
 - OS: All
 - IDE: All

## Additional information ##

Seems like a blank value is allowed only for resetting operations, i.e. only for CLEAR

**Comment by grianbrcom** [comment]
I'll try to fix it.
