### ISSUE TITLE
Fix All the Compilation Warnings in Java Part

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#697]
## Description ##
The server contains a lot of Java compilation warnings. They should be fixed when possible.

## Acceptance Criteria ##
- All the data bus warnings are fixed
- All the `CobolErrorStrategy` warnings are fixed
- All the raw `Class` calls are parametrized
- All the unused imports and fields are removed
![image (10)](https://user-images.githubusercontent.com/47776865/101467153-3f721d00-3942-11eb-9b00-7bc0db629a02.png)

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

## Technical details ##
The Guice warning is a platform limitation.

**Comment by grianbrcom** [comment]
I'll do it.
