### ISSUE TITLE
Support IDMS DML

### ISSUE THREAD

**Issue by temanbrcom** [eclipse/che-che4z-lsp-for-cobol#704]
**Is your feature request related to a problem?**

I would like COBOL LS to support IDMS DML in order to check the syntax of those statements. 

**Describe the solution you'd like**

COBOL LS treats IDMS DML statements as a part of the COBOL syntax and applies all the meaningful syntax and semantic checks.

**Comment by schte01** [comment]
The IDMS X team is collaborating on this.
