### ISSUE TITLE
Redesign Cobol Grammars

### ISSUE THREAD

**Issue by asatklichov** [eclipse/che-che4z-lsp-for-cobol#710]
## Description ##
As a USER, I would like to have core Cobol grammar as a base and build onto it cics, sql and etc grammars so I can have an option of using Cobol grammar itself separately. 

## Acceptance Criteria ##
-  All tests must pass and no migration issue  

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

## Technical details ##
I want to have a core Cobol grammar and build cics, sql on top of it.  So I can use my core Cobol separately and have a  full control to manage cics or sql separately.

**Comment by temanbrcom** [comment]
Linked to #264
