### ISSUE TITLE
Snippets scope

### ISSUE THREAD

**Issue by grianbrcom** [eclipse/che-che4z-lsp-for-cobol#726]
## Description ##
Our [snippets.json](https://github.com/eclipse/che-che4z-lsp-for-cobol/blob/development/clients/cobol-lsp-vscode-extension/snippets.json) file has different scopes:
- cobol
- cobol,acucobol
- cobol,acucobol,opencobol,gnucobol
- (without a scope)

## Acceptance Criteria ##
- Decide which scope we will use (I suggest just a cobol)
- The snippets.json file will be refactored according to this decision.

## Definition of Done ##
- The story is implemented according to the description.
- Unit testing done (Preferably by TDD approach, coverage should be at least 70%).
- Code review done by at least one other team member.
- Manual testing is done.
- Documentation is added and reviewed (if needed).
- The pull request is approved.
- The story is merged into the development branch.
- Tests are performed on the development branch.

**Comment by zimlu02** [comment]
Fixed in the upcoming release 1.1.0
