### ISSUE TITLE
Support copybooks outside the current workspace

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-lsp-for-cobol#755]
**Describe the solution you'd like**

I want to be able to specify copybooks outside the current workspace (using "../" ).

Copybooks outside the workspace won't be monitored for changes by the plugin though so that it doesn't decrease the performance.

**Acceptance criterias**

- support copybooks located outside the current workspace
- user can provide a path up the current folder using  "../"
- copybooks outside the workspace are not monitored for changes

**Describe alternatives you've considered**

How about supporting absolute paths?

**Comment by grianbrcom** [comment]
Done by #773.
