### ISSUE TITLE
[UI_tests] Cypress creates empty video about test run

### ISSUE THREAD

**Issue by grianbrcom** [eclipse/che-che4z-lsp-for-cobol#761]
## Description ##

Cypress creates a report about the test run process in folder `che-che4z-lsp-for-cobol/tests/cypress/videos/LSP/`. All video files are empty.

## Steps to reproduce ##

1. Run any Cypress test wait for the end.
2. Go to `che-che4z-lsp-for-cobol/tests/cypress/videos/LSP/` and open any file.

## Expected behavior ##

The video file must contain the whole testing process.

## Environment ##
 
OS: Linux Arch, Windows 10

## Additional information ##
I've tried to run tests in headless mode. And enable/disable `--reporter mochawesome` param.

**Comment by nalmabrcom** [comment]
According to this [issue](https://github.com/cypress-io/cypress/issues/9265) it is, unfortunately, reproducible on Cypress less v6.0.1 (currently we have v5.3.0) and Chrome >87. 
Please close this issue, I've created the appropriate [one](https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/765).

**Comment by grianbrcom** [comment]
Thanks for your investigation. Now it's clear what must be done to fix the issue. But Cypress still produces empty videos. I think that it will be better to close both issues when Cypress will be upgraded.

**Comment by grianbrcom** [comment]
Closed by #774
