### ISSUE TITLE
copyrights update 

### ISSUE THREAD

**Issue by asatklichov** [eclipse/che-che4z-lsp-for-cobol#789]
## Description ##
 
As a stakeholder, I want all instances of copyrights to contain the actual year (e.g. 2021) for all supported extensions (E4E, DAP, LSP for COBOL, LSP for HLASM).
Links: [ip-copyright-headers](https://www.eclipse.org/projects/handbook/#ip-copyright-headers), [cawiki.ca.com](https://cawiki.ca.com/pages/viewpage.action?spaceKey=AU&title=IntelliJ+Idea)

**NOTE:**  As discussed in standup meeting, we will keep the year '2020' for now, even on newly created files. 
            If license change is needed then we need to make it via lawyers.

**Comment by ishche** [comment]
There is a link to the ca wiki, which still unavailable for the public.

**Comment by ishche** [comment]
From the first link, there is a statement:
Copyright statements take the form Copyright (c) {year} {owner}.
The {year} is the year in which the content was created

For me, it sounds like we do need to put the right date in the license header.

**Comment by asatklichov** [comment]
> This topic is discussed, and agreed to do it like that. You can open it for discussion again.

**Comment by ishche** [comment]
> You can open it for discussion again.

That is exactly what I've done :)
We should discuss it here.

**Comment by asatklichov** [comment]
As per discussion, newly created files should have copyright to contain the actual year
