### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by flacherez** [eclipse/che-che4z-lsp-for-cobol#810]
- Issue Type: `Performance`
- Extension Name: `cobol-language-support`
- Extension Version: `0.17.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\flach\AppData\Local\Temp\BroadcomMFD.cobol-language-support-unresponsive.cpuprofile.txt`
[BroadcomMFD.cobol-language-support-unresponsive.cpuprofile.txt](https://github.com/eclipse/che-che4z-lsp-for-cobol/files/6119056/BroadcomMFD.cobol-language-support-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by temanbrcom** [comment]
Thank you for reporting this issue! It should be fixed in 0.19.0.
