### ISSUE TITLE
Remove Cobol-85 Obsolete Elements 

### ISSUE THREAD

**Issue by asatklichov** [eclipse/che-che4z-lsp-for-cobol#821]
## Description ##
As a USER I would like not to not see Cobol-85 Obsolete elements in Cobol Language Support extension.  

## Acceptance Criteria ##
- AC #1 No Regression issue 
- AC #2 Obsolete elements must not exist  
 

## Technical details ##
Remove all those Cobolm85 obsolete elements

**Comment by zimlu02** [comment]
Part of the next release 1.1.0.
