### ISSUE TITLE
Syntax errors when IDMS ready statements are within an IF block

### ISSUE THREAD

**Issue by Oxdeception** [eclipse/che-che4z-lsp-for-cobol#952]
## Description ##
IDMS ready statements have syntax errors when inside an if block. This should be valid syntax as IDMS uses `;` instead of `.` to end generated ready statement code within an if block.

## Screenshots ##
![image](https://user-images.githubusercontent.com/30361731/122097577-d4683e00-cddd-11eb-814e-bd266e21252b.png)

## Environment ##
 - OS: Windows 10, Manjaro Linux
 - IDE: VS Code

**Comment by temanbrcom** [comment]
Hi @Oxdeception,

Thank you for reporting! I reproduced this issue and going to fix it before the next release.
