### ISSUE TITLE
Syntax error on multiline comment-entry for optional paragraphs in identification division

### ISSUE THREAD

**Issue by Oxdeception** [eclipse/che-che4z-lsp-for-cobol#953]
## Description ##
Syntax errors are given for comment entries on optional, identification area paragraphs if they contain span multiple lines.

## Screenshots ##
![image](https://user-images.githubusercontent.com/30361731/122099547-1e522380-cde0-11eb-8ca4-1de4de54c41d.png)
![image](https://user-images.githubusercontent.com/30361731/122099633-39249800-cde0-11eb-8f6f-3804d28d4dd2.png)

## Environment ##
 - OS: Windows 10, Manjaro Linux
 - IDE: VS Code

## Additional information ##
Per IBM COBOL language reference: 

> The comment-entry in any of the optional paragraphs can be any combination of characters from the
> character set of the computer. The comment-entry is written in Area B on one or more lines.

**Comment by temanbrcom** [comment]
Hi @Oxdeception,

I see we are not following the specification here. I will fix it.
Thank you for reporting!
