### ISSUE TITLE
Resolve IDMS records

### ISSUE THREAD

**Issue by Oxdeception** [eclipse/che-che4z-lsp-for-cobol#954]
**Is your feature request related to a problem?**
IDMS COPY statements produce neither syntax or missing copybook errors, however the records or code they should provide do cause a large amount of "Invalid definition for:"  and "The following paragraph is not defined:" errors which make it difficult to locate legitimate errors in programs that make heavy use of IDMS.

**Describe the solution you'd like**
Resolve IDMS records from a specified local copybook location. While not the most convenient solution for users, this is likely the simplest. 

**Describe alternatives you've considered**
- Command or option to suppress invalid definition errors.
- Option to specify an IDMSRPTS schema report file(s) to provide information for IDMS validations.

**Comment by temanbrcom** [comment]
Hi @Oxdeception 

Thank you for reporting this issue! I am pleased to let you know that the feature to resolve IDMS records is currently in progress and will be available in one of the nearest releases. 

Thank!

**Comment by Oxdeception** [comment]
Thank you very much

**Comment by NakeshaNewbury** [comment]
Hello @Oxdeception 

I'm the Product Owner for CA IDMS.  Thank you for trying out our CA IDMS COBOL DML support within the extension!  We will be releasing more functionality in July for our IDMS syntax support.  We are now looking to include support for IDMS Copybooks and would appreciate talking to IDMS users to get their perspective and requirements.  Would you be willing to do a meeting with us?  If so, please reach out to me at Nakesha.Newbury@broadcom.com.

Thank you very much!

**Comment by temanbrcom** [comment]
The pull request is merged. It will appear in the next release. 
Thank you!
