### ISSUE TITLE
VS Code File Associations with File Path doesn't work

### ISSUE THREAD

**Issue by MocniMax** [eclipse/che-che4z-lsp-for-cobol#955]
Hello,

I am trying to properly configure VSCode COBOL extension but have some issues with it :((.
One of them is related to file associations to modules with no extensions (as are on zOS).

We copy our zOS development to Windows and AIX to develop and port/test all code to work on all supported platforms. Therefore, modules must be the same and have exact same names i.e. without extensions.
When I use IBM Z Open Editor, following file assassination settings work correctly and all my COBOL modules and copybooks are correctly recognized as COBOL ones and proper language server is active. Unfortunately, COBOL Language Support doesn't.  
HEre is my setting:

    "files.associations": {
        "*.COBOL*": "cobol",
        "*.COB*": "cobol",
        "*.COBCOPY*": "cobol",
        "*.COPYBOOK*": "cobol",
        "*.COPY*": "cobol",
        "*.PL1*": "pl1",
        "*.PLI*": "pl1",
        "*.INC*": "pl1",
        "*.INCLUDE*": "pl1",
        "*.JCL*": "jcl",
        "***/JCL/**": "jcl",
        "*.ASM*": "hlasm",
        "*.ASSEMBLE*": "hlasm",
        "*.HLASM*": "hlasm",
        "*.HLA*": "hlasm",
        "**/H/*": "c",
        "**/C/*": "c",
        "**/JCL/*": "jcl",
        "**/COBOL/*": "cobol"

Any idea why this happens?

Regards :)

**Comment by temanbrcom** [comment]
Hi @MocniMax,

Please, try using "COBOL" instead of "cobol" and "COBOL Copybook" for directories that are expected to contain copybooks. Please, notice that the language IDs in the `files.associations` section are case-sensitive. 
The settings that you have provided are produced by the IBM Z Open Editor extension, and may not fully match our requirements.
Thank you.

**Comment by MocniMax** [comment]
Hi @**temanbrcom** ,

After I changed all file.associations from "cobol" to "COBOL" and added "COBOL Copybook" all my COBOL sources are recognized correctly.

Thanks a lot!

**Comment by temanbrcom** [comment]
You are welcome! I'm glad it helps. I'm closing the issue.
