### ISSUE TITLE
Opening COPYBOOK reports Source text cannot go past column 80 at line 01

### ISSUE THREAD

**Issue by MocniMax** [eclipse/che-che4z-lsp-for-cobol#964]
Hi,

I have another issue now.

If I open any COPYBOOK file it gets an 1+ in its tab and last character of its first line is marked with following error:

Source text cannot go past column 80 COBOL Language Support - E

The only way to remove it is to change its Language to COBOL and then to COBOL Copybook again.

Additionally, looks like COPYBOOK is not analyzed if no COBOL module is open. 

Log is attached.
[app.log](https://github.com/eclipse/che-che4z-lsp-for-cobol/files/6677433/app.log)

Any idea?

**Comment by temanbrcom** [comment]
Hi @MocniMax, please, show me the first line of that copybook.

**Comment by temanbrcom** [comment]
Also, please, notice that the copybooks are analyzed only when they are [referenced from a COBOL document](https://github.com/eclipse/che-che4z-lsp-for-cobol#copybook-support). 
The analysis of the copybook files themselves is not implemented yet. 
Thank you!

**Comment by MocniMax** [comment]
It is the same in each of our copybooks, beginning of module header, 72 * followed by eight blanks.
Here it is:
`******************************************************************        `

All of our modules starts with module header surrounded with two of those lines (one for start and one for end of header block).

**Comment by temanbrcom** [comment]
Ok, I reproduced it. Seems like a bug. Thank you for reporting!

**Comment by temanbrcom** [comment]
I'm sorry for the long response, the CI/CD was failing. Please, try if this build works fine: https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/fix-copybook-encoding/7/artifact/cobol-language-support-0.19.0+fix-copybook-encoding.7.vsix
Thank you!

**Comment by MocniMax** [comment]
Good morning,

No problem at all. I always wished so called Official Professional Support is at least a bit responsive as any of our Open Source Projects is :)).

It looks OK now. Will continue with my usage tests.

Thanks a lot, again :)).

**Comment by temanbrcom** [comment]
Thank you! This fix goes to the upcoming release this week. Please, enable auto-update for extensions to get the latest version.
And don't hesitate to report new bugs - it helps to keep the high quality a lot! 
Thanks!

**Comment by MocniMax** [comment]
Already did, thanks for a reminder.

Always, I am actively using Code for my zOS and AIX C, COBOL, JCL, scripts and DB2 development testing.
