### ISSUE TITLE
Copy replacing does not correctly maintain areas

### ISSUE THREAD

**Issue by Oxdeception** [eclipse/che-che4z-lsp-for-cobol#974]
## Description ##
When using a copy replacing statement for a copybook that has comment area numbering, the comment area is shifted into area B if the replaced text is longer than the replacing text. Errors also occur when the replacing text would make the line too long.

## Expected behavior ##
Comment and sequence area characters are not moved by the copy statement, line continuations are used when needed.

## Screenshots ##
![image](https://user-images.githubusercontent.com/30361731/122950757-b739ef00-d34a-11eb-9f18-0664cf974da6.png)
![image](https://user-images.githubusercontent.com/30361731/122954093-26184780-d34d-11eb-81a2-993c24b87808.png)

## Environment ##
 - OS: Windows 10, Manjaro Linux
 - IDE: VS Code

## Additional information ##
The COBOL compiler will add spaces and line continuations when needed to ensure that copied text remains in the correct area.

**Comment by temanbrcom** [comment]
Thank you for the reporting! 
The fix will appear in the next release.

**Comment by ap891843** [comment]
PR raised
